- .gitignore
added a line in gitignore to ignore the configs of your vscode
> ignoring configs

- app/controllers/instruments_controller.rb
authorize no logged users to have access to index and show
> fix: authorize pages for no log in / sign up users

- app/assets/stylesheets/application.scss
- app/views/instruments/show.html.erb
Création de la page SHOW pour les instruments avec du bootstrap et du css
> Made show page and added css in application.css

- config/environments/production.rb
> config cloudinary for prod

- app/controllers/bookings_controller.rb
- app/models/instrument.rb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- config/routes.rb
- db/seeds.rb
- test/controllers/bookings_controller_test.rb
Create BookingsController and add index, show, new and create routes
> bookings controller and routes

- app/controllers/instruments_controller.rb
- app/views/instruments/show.html.erb
Ajouter les images sur la show
> ajouter les images

- db/seeds.rb
Jeremy, 
j'ai ajouté 4 autres users. 
j'ai également, changé les adresses de tous les users, ils sont tous dans le premier arrondissement !
et y'a egalement ta modif de tout à l'heure sur les photos !
> modify_seed_a_jour

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/controllers/index.js
- app/views/shared/_navbar.html.erb
update dropdown and add category in dropdown
> update navbar bug and add create element dropdown

- app/controllers/instruments_controller.rb
- app/models/instrument.rb
- app/views/instruments/_form.html.erb
- app/views/instruments/create.html.erb
- app/views/instruments/index.html.erb
- app/views/instruments/new.html.erb
fix the link_to nouvel instrument in index page
>  fix the link_to in index page

- app/views/instruments/index.html.erb
- app/views/instruments/show.html.erb
Fix dynamic info on show
Fix map size
> Fix show and map size

- app/views/instruments/_form.html.erb
- app/views/shared/_navbar.html.erb
> update link in navbar create instrument

- db/schema.rb
Reverts Jeremy-Lgn/airbnbeat#25
because it's a. mistake
> Revert "j'ai_resolu_le_bug"

- app/controllers/instruments_controller.rb
- app/views/instruments/_review.html.erb
- app/views/instruments/show.html.erb
- trument = Instrument.find(<id_of_instrument>)
ajout des avis et d'une note moyenne, le tout dynamique
> added review section

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_show.scss
- app/javascript/controllers/lightbox_controller.js
- app/javascript/controllers/toggle_controller.js
- app/views/bookings/_form_booking.html.erb
- app/views/bookings/_success_booking.html.erb
- app/views/instruments/show.html.erb
> Update show page

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_search_bar.scss
- app/views/instruments/index.html.erb
Make better view for index page
> update alignements, hide scroll bar and center search bar and style it

- app/assets/stylesheets/components/_show.scss
- app/controllers/bookings_controller.rb
- app/javascript/controllers/booking_calculator_controller.js
- app/javascript/controllers/submit_booking_controller.js
- app/views/bookings/_form_booking.html.erb
- app/views/bookings/_success_booking.html.erb
- app/views/instruments/show.html.erb
edit show page add better reswervation flow
> Update show page pt 2

- app/assets/stylesheets/components/_show.scss
- app/javascript/controllers/submit_booking_controller.js
- app/views/instruments/show.html.erb
Add in the div infos reservation form
> fix console.log and show view

- app/javascript/controllers/booking_calculator_controller.js
Remove caution on calcul of the price
> fix no caution

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_my_instrument.scss
- app/views/instruments/index.html.erb
- app/views/pages/my_instruments.html.erb
> fix overflow button index page and correct title for my instruments

- app/assets/stylesheets/components/_show.scss
- app/views/instruments/show.html.erb
change title position and content
> modify title

- app/views/shared/_instrument.html.erb
fix remove sample replace by first
> fix image sample

- app/views/instruments/show.html.erb
Hide button "Réservez le" if not login
> fix booking display if log out

- app/assets/stylesheets/components/_index.scss
- app/views/instruments/index.html.erb
> resolution de mes merdes

- db/seeds.rb
BRUNOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> yolo pt. 2
